services:
  jse-avocats-bdd:
    container_name: jse-avocats-bdd
    image: mysql:8.0
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bddwp
      MYSQL_ROOT_PASSWORD: root

  jse-avocats-wp:
    container_name: jse-avocats-wp
    image: ghcr.io/oc-for-students/jse-avocats:latest
    ports:
      - 8081:80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      WORDPRESS_DB_HOST: jse-avocats-bdd
      WORDPRESS_DB_NAME: bddwp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
  
volumes:
  db_data:
